"""phase1 schema alignment

Revision ID: 018c6b4ce3e1
Revises: 1ed43cbdcb5d
Create Date: 2026-07-10 18:35:38.245153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '018c6b4ce3e1'
down_revision: Union[str, Sequence[str], None] = '1ed43cbdcb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_FEATURE_STATUS_SQL = (
    "CASE WHEN score = 0 THEN 'unstarted' WHEN score < 75 THEN 'inprogress' "
    "WHEN score < 100 THEN 'revisiting' ELSE 'completed' END"
)
_CONTAINER_STATUS_SQL = (
    "CASE WHEN score = 0 THEN 'unstarted' WHEN score <= 30 THEN 'beginner' "
    "WHEN score <= 60 THEN 'intermediary' WHEN score <= 90 THEN 'advanced' ELSE 'fluent' END"
)
_COMPONENT_STATUS_SQL = (
    "CASE WHEN score = 0 THEN 'unseen' WHEN score <= 10 THEN 'introduced' "
    "WHEN score <= 50 THEN 'learning' WHEN score <= 75 THEN 'practicing' "
    "WHEN score <= 90 THEN 'review' ELSE 'mastered' END"
)
# Tables whose `status` generated column was wrongly inherited from the
# container/language formula and needs the feature-style thresholds instead.
_FEATURE_STATUS_TABLES = ('lesson', 'vocabulary', 'grammar', 'calligraphy', 'exercise')
# Tables whose `status` generated column was wrongly inherited from the
# container/language formula and needs the component-style thresholds instead.
_COMPONENT_STATUS_TABLES = ('word', 'character', 'passage')


def _recreate_status_column(table: str, case_sql: str) -> None:
    # Postgres generated columns can't be ALTERed in place (no ALTER COLUMN ...
    # SET EXPRESSION) - drop and re-add. Postgres only supports STORED, not
    # SQLite's VIRTUAL, generated columns.
    op.drop_column(table, 'status')
    op.execute(
        f"ALTER TABLE {table} ADD COLUMN status TEXT "
        f"GENERATED ALWAYS AS ({case_sql}) STORED"
    )


def upgrade() -> None:
    """Upgrade schema."""
    for _table in _FEATURE_STATUS_TABLES:
        _recreate_status_column(_table, _FEATURE_STATUS_SQL)
    for _table in _COMPONENT_STATUS_TABLES:
        _recreate_status_column(_table, _COMPONENT_STATUS_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calligraphy', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('calligraphy', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('calligraphy', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('character', 'phonetic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('character', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('character', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('commitment_log', 'total_time_ms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('daily_stats', 'time_studied_ms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('exercise', 'exercise_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('exercise', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('exercise', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('grammar', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('grammar', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('grammar', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('language', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('language', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('language', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_language_user_name', 'language', ['user_id', 'name'])
    op.alter_column('lesson', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lesson', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('passage', 'translation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('passage', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('passage', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('passage', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('source', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='created_at::timestamp',
               existing_nullable=False)
    op.alter_column('source', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='updated_at::timestamp',
               existing_nullable=True)
    op.alter_column('tag', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='created_at::timestamp',
               existing_nullable=False)
    op.alter_column('tag', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='updated_at::timestamp',
               existing_nullable=True)
    op.create_unique_constraint('uq_tag_user_name', 'tag', ['user_id', 'name'])
    op.alter_column('user_preferences', 'daily_goal_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_preferences', 'last_updated',
               existing_type=sa.DateTime(),
               type_=sa.Date(),
               postgresql_using='last_updated::date',
               existing_nullable=True)
    op.alter_column('vocabulary', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('vocabulary', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('vocabulary', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('word', 'translation',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('word', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('word', 'image_files',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('word', 'audio_files',
               existing_type=sa.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    for _table in _FEATURE_STATUS_TABLES:
        _recreate_status_column(_table, _CONTAINER_STATUS_SQL)
    for _table in _COMPONENT_STATUS_TABLES:
        _recreate_status_column(_table, _CONTAINER_STATUS_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('word', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('word', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('word', 'translation',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('vocabulary', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('vocabulary', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('vocabulary', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('user_preferences', 'last_updated',
               existing_type=sa.Date(),
               type_=sa.DateTime(),
               postgresql_using='last_updated::timestamp',
               existing_nullable=True)
    op.alter_column('user_preferences', 'daily_goal_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_tag_user_name', 'tag', type_='unique')
    op.alter_column('tag', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               postgresql_using='updated_at::varchar',
               existing_nullable=True)
    op.alter_column('tag', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               postgresql_using='created_at::varchar',
               existing_nullable=False)
    op.alter_column('source', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               postgresql_using='updated_at::varchar',
               existing_nullable=True)
    op.alter_column('source', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               postgresql_using='created_at::varchar',
               existing_nullable=False)
    op.alter_column('passage', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('passage', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('passage', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('passage', 'translation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lesson', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lesson', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_language_user_name', 'language', type_='unique')
    op.alter_column('language', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('language', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('language', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grammar', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('grammar', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('grammar', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('exercise', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('exercise', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('exercise', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('exercise', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise', 'exercise_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('daily_stats', 'time_studied_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('commitment_log', 'total_time_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('character', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('character', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('character', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('character', 'phonetic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('calligraphy', 'audio_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('calligraphy', 'image_files',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('calligraphy', 'difficulty',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
